import localFont from "next/font/local";
import "./globals.css";
import BlogHeader from "./components/BlogHeader";
import { blogTitle } from "./const";

export const metadata = {
  title: blogTitle,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BlogHeader />
        {children}
      </body>
    </html>
  );
}
